<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>404 大神驾到</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">首页</a></li>
                    <li class="breadcrumb-item active">404 大神</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="error-page">
        <h2 class="headline text-warning"> 404</h2>

        <div class="error-content">
            <h3><i class="fas fa-exclamation-triangle text-warning"></i> 大神驾到～ 闲杂人等退散～</h3>

            <p>等闲之事，大神不会光临，请检查</p>
        </div>
        <!-- /.error-content -->
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="card-widget card-blue">
            <div class="card-header">环境参数</div>
            <div class="card-body">
                <?php
                echo nl2br(print_r($_SERVER,true));
                ?>
            </div>
        </div>
        <div class="card-widget card-danger">
            <div class="card-header">错误信息</div>
            <div class="card-body">
                <?php
                echo nl2br(print_r($this->errors,true));
                ?>
            </div>
        </div>
    </div>
    <!-- /.error-page -->
</section>
<!-- /.content -->