<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>500 内部故障</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">首页</a></li>
                    <li class="breadcrumb-item active">500 内部故障</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="error-page">
        <h2 class="headline text-danger">500</h2>

        <div class="error-content">
            <h3><i class="fas fa-exclamation-triangle text-danger"></i> 估计是哪里代码出错了</h3>
            <?php
            if (isset($this->showExceptions) && $this->showExceptions)
            {
                ?>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card-widget card-blue">
                            <div class="card-header"><?php if (isset($this->exception)) {
                                    echo $this->exception->getMessage();
                                }?></div>
                            <div class="card-body">
                                <?php
                                if (isset($this->exception)) {
                                    echo $this->exception->getTraceAsString();
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
            }
            ?>
            <p>欢迎你到 <a href="https://github.com/millsguo/subtrans/issues/" target="_blank">GITHUB</a> 反馈</p>
        </div>
    </div>
    <!-- /.error-page -->
    <div class="clearfix"></div>
    <div class="row">
        <div class="card-widget card-blue">
            <div class="card-header">环境参数</div>
            <div class="card-body">
                <?php
                var_dump($_SERVER);
                ?>
            </div>
        </div>
    </div>
</section>
<!-- /.content -->