<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>错误信息</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">首页</a></li>
                    <li class="breadcrumb-item active">错误信息</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="error-page">
        <h2 class="headline text-danger"><?php echo $this->messageType ?? '错误';?></h2>

        <div class="error-content">
            <h3><i class="fas fa-exclamation-triangle text-danger"></i> <?php echo $this->messageTitle ?? '错误信息';?></h3>
            <p><?php echo $this->message;?></p>
            <p>欢迎你到 <a href="https://github.com/millsguo/subtrans/issues/" target="_blank">GITHUB</a> 反馈</p>
        </div>
    </div>
    <!-- /.error-page -->

</section>
<!-- /.content -->