<!DOCTYPE html>
<html lang="zhCN">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('subtrans字幕翻译管理')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php
    $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

    echo $this->headStyle();
    echo $this->headMeta();
    echo $this->headLink();
    ?>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet"
          href="/static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/static/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- SweetAlert2 -->
    <link rel="stylesheet"
          href="/static/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">
    <!-- Toastr -->
    <link rel="stylesheet" href="/static/plugins/toastr/toastr.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="/static/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- DateRange picker -->
    <link rel="stylesheet" href="/static/plugins/daterangepicker/daterangepicker.css">
    <!-- summerNote -->
    <link rel="stylesheet" href="/static/plugins/summernote/summernote-bs4.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- Common Style -->
    <link rel="stylesheet" href="/scripts/css/common-v1.css">
</head>
<body class="hold-transition sidebar-mini dark-mode">
<div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-light bg-dark border-bottom-0">
        <!-- Left navbar links -->
        <!--
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="/" class="nav-link">首页</a>
            </li>
        </ul>
        -->
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
            <i class="fas fa-search"></i>
        </a>
        <!-- SEARCH FORM -->
        <div class="navbar-search-block navbar-search-open" style="display: flex;">
            <form class="form-inline" action="/search/">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="搜索" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                        <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Notifications Dropdown Menu -->
            <!--
            <li class="nav-item">
                <span class="nav-link">用户
                </span>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                    <i class="fas fa-th-large"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/accounts/logout/">
                    退出
                </a>
            </li>
            -->
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-dark-purple border-bottom-0">
        <!-- Brand Logo -->
        <a href="/" class="brand-link navbar-dark text-center border-bottom-0">
            <span class="brand-text font-weight-light text-white">字幕管理&翻译</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar" style="margin-top: 22px;">
            <!-- Sidebar user panel (optional) -->
            <!--
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">用户</a>
                </div>
            </div>
            -->
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <?php
                echo $this->partial('menu.phtml', ['controller' => $this->controller]);
                ?>
            </nav>
            <div class="text-center" style="width:150px;height:40px;position: fixed;bottom:10px;left:50px;">Version
                <?php
                echo EasySub\Tools\Config::getVersion();
                ?>
            </div>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>
    <div class="content-wrapper bg-dark" style="min-height: 707px;">
        <!-- Content Header (Page header) -->
        <div class="content-header">
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <?php
                echo $this->layout()->content;
                ?>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2022-<?= date('Y'); ?> millsguo </strong> <a href="https://github.com/millsguo/subtrans/" target="_blank" class="btn btn-info btn-xs">https://github.com/millsguo/subtrans/</a>
    </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="/static/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- SweetAlert2 -->
<script src="/static/plugins/sweetalert2/sweetalert2.min.js"></script>
<!-- Toastr -->
<script src="/static/plugins/toastr/toastr.min.js"></script>
<!-- InputMask -->
<script src="/static/plugins/moment/moment.min.js"></script>
<script src="/static/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/dist/js/adminlte.min.js"></script>
<!-- Common Script -->
<script src="/static/dist/js/common.js"></script>
<!-- Subtrans Script -->
<script src="/scripts/js/common.js"></script>
<!-- Message Script -->
<script type="text/javascript">
    <?php
    if (isset($this->message)) {
        if (isset($this->messageType)) {
            switch ($this->messageType) {
                case 'success':
                    $type = 'bg-' . $this->messageType;
                    $msgIcon = 'fa-check-circle';
                    $firstLang = '恭喜';
                    break;
                case 'error':
                case 'danger':
                    $type = 'bg-danger';
                    $msgIcon = 'fa-times-circle';
                    $firstLang = '错误';
                    break;
                case 'info':
                    $type = 'bg-' . $this->messageType;
                    $msgIcon = 'fa-info-circle';
                    $firstLang = '提醒';
                    break;
                case 'warning':
                    $type = 'bg-' . $this->messageType;
                    $msgIcon = 'fa-exclamation-circle';
                    $firstLang = '警告';
                    break;
                default:
                    $type = '';
                    $firstLang = '';
                    $msgIcon = '';
                    break;
            }
        } else {
            $type = 'bg-info';
            $firstLang = '';
            $msgIcon = '';
        }
        if (is_array($this->message)) {
            foreach ($this->message as $message) {
                echo 'showToasts({title:"' . $firstLang . '",body:"' . $message . '",icon:"fa ' . $msgIcon . ' fa-lg",class:"' . $type . '"});';
            }
        } else {
            echo 'showToasts({title:"' . $firstLang . '",body:"' . $this->message . '",icon:"fa ' . $msgIcon . ' fa-lg",class:"' . $type . '"});';
        }
    }
    ?>
</script>
<?php echo $this->headScript() ?>
<script type="text/javascript">
    <?php
    echo $this->placeholder('footerScript');
    ?>
</script>
</body>
</html>