<div class="dataTables_paginate paging_simple_numbers" id="pageControlBox">
    <ul class="pagination">
        <li class="paginate_button page-item previous disabled" id="page_previous">
            <a href="#" tabindex="0" class="page-link">上一页</a>
        </li>
        <li class="paginate_button page-item active">
            <a href="#" data-dt-idx="1" tabindex="0"
               class="page-link">1</a>
        </li>
        <li class="paginate_button page-item ">
            <a href="#" data-dt-idx="2" tabindex="0"
               class="page-link">2</a>
        </li>
        <li class="paginate_button page-item ">
            <a href="#" data-dt-idx="3" tabindex="0"
               class="page-link">3</a>
        </li>
        <li class="paginate_button page-item ">
            <a href="#" data-dt-idx="4" tabindex="0"
               class="page-link">4</a>
        </li>
        <li class="paginate_button page-item ">
            <a href="#" data-dt-idx="5" tabindex="0"
               class="page-link">5</a>
        </li>
        <li class="paginate_button page-item ">
            <a href="#" data-dt-idx="6" tabindex="0"
               class="page-link">6</a>
        </li>
        <li class="paginate_button page-item next" id="page_next">
            <a href="#" data-dt-idx="7" tabindex="0" class="page-link">下一页</a>
        </li>
    </ul>
</div>