<div class="card card-primary w-full h-full">
    <div class="card-header">
        <?php echo $this->seasonRow->title ?? '';?><span class="badge badge-warning" style="margin-left: 20px;"><?php echo $this->seasonRow->year ?? '';?></span>
        <div class="card-tools">
            <a href="#" onclick="addTask('season','',<?php echo $this->seasonRow->id ?? 0;?>);" class="btn btn-success btn-sm">扫描全季</a>
        </div>
    </div>
    <div class="card-body">
        <?php
        echo $this->partial('section/video-tv.phtml',['rows' => $this->episodeArray]);
        ?>
    </div>
</div>