<div class="card card-widget widget-user-2 shadow-sm mt-5 bg-white">
    <div class="card-header bg-info">
        <h3 class="card-title">信息</h3>
    </div>
    <div class="card-body p-0 bg-white">
        <table class="table">
            <tbody>
            <?php
            if (!empty($this->row->runtime)) {
                echo '<tr><td>时长</td><td class="text-right">' . $this->row->runtime . '分</td></tr>';
            }
            if (!empty($this->row->imdb_id)) {
                echo '<tr><td>IMDB</td><td class="text-right"><a href="https://www.imdb.com/title/' . $this->row->imdb_id . '" class="" target="_blank">' . $this->row->imdb_id . '</td></tr>';
            }
            if (!empty($this->row->tmdb_id)) {
                echo '<tr><td>TMDB</td><td class="text-right"><a href="https://www.themoviedb.org/movie/' . $this->row->tmdb_id . '" class="" target="_blank">' . $this->row->tmdb_id . '</td></tr>';
            }
            if (!empty($this->row->tvdb_id)) {
                echo '<tr><td>TVDB</td><td class="text-right"><a href="https://www.thetvdb.com/dereferrer/series/' . $this->row->tvdb_id . '" target="_blank">' . $this->row->tvdb_id . '</a></td></tr>';
            }
            if (!empty($this->nfoData['releasedate'])){
                ?>
                <tr>
                    <td>上映时间</td>
                    <td class="text-right"><?php echo $this->nfoData['releasedate'];?></td>
                </tr>
                <?php
            }
            if (!empty($this->nfoData['country'])) {
                ?>
                <tr>
                    <td>国家</td>
                    <td class="text-right"><?php
                        if (is_array($this->nfoData['country'])) {
                            foreach ($this->nfoData['country'] as $country) {
                                echo $country . ' &nbsp;';
                            }
                        } else {
                            echo $this->nfoData['country'];
                        }
                        ?></td>
                </tr>
                <?php
            }
            if (!empty($this->nfoData['studio'])) {
                echo '<tr><td>公司</td><td class="text-right">' . $this->nfoData['studio'] . '</td></tr>';
            }
            ?>
            </tbody>
        </table>
    </div>
</div>