<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">电影</h3>
        <div class="card-tools">
            <a href="#" onclick="addTask('all','movie',0);" class="btn btn-success btn-sm">扫描电影库</a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <div class="row">
            <?php
            if (is_countable($this->rows) && count($this->rows) > 0) {
                foreach ($this->rows as $row) {
            ?>
            <div class="image-box">
                <a href="/movie/show/id/<?php echo $row->id;?>">
                <div class="position-relative bg-gray rounded-xl overflow-hidden w-full h-full border-width-2">
                    <img src="/image/show?w=185&h=300&code=<?php echo base64_encode($row->file_path . '/poster.jpg'); ?>" alt="" class="img-fluid h-full w-full">
                    <?php
                    if ((int)$row->have_zh_sub === 1) {
                    ?>
                    <div class="ribbon-wrapper ribbon-lg">
                        <div class="ribbon bg-success">
                            中文字幕
                        </div>
                    </div>
                    <?php
                    }
                    ?>
                </div>
                <div class="video-tag-line">
                    <div class="video-tag bg-warning"><?php echo $row->rating; ?>分</div>
                    <div class="video-tag bg-info"><?php echo $row->year;?>年</div>
                </div>
                <div class="text-center"><?php echo htmlentities($row->title);?></div>
                </a>
            </div>
            <?php
                }
            }
            ?>
        </div>
    </div>
    <!-- /.card-body -->
</div>