<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">电影</h3>
        <div class="card-tools">
            <a href="/movie/scan/target/all/" class="btn btn-success btn-sm">扫描电影库</a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <div class="row">
            <?php
            if (is_countable($this->rows) && count($this->rows) > 0) {
                foreach ($this->rows as $row) {
            ?>
            <div class="col-sm-3" style="width: 200px;height: 300px;">
                <div class="position-relative p-3 bg-gray" style="border-radius: .75rem!important;height: 180px">
                    <img src="../../dist/img/photo1.png" alt="Photo 1" class="img-fluid">
                    <?php echo $row->title;?> <br>
                    <small><?php echo $row->year;?></small>
                </div>
            </div>
            <?php
                }
            }
            ?>
        </div>
    </div>
    <!-- /.card-body -->
</div>