<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">电影</h3>
        <div class="card-tools">
            <a href="/movie/scan/target/all/" class="btn btn-success btn-sm">扫描电影库</a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <div class="row">
            <?php
            if (is_countable($this->rows) && count($this->rows) > 0) {
                foreach ($this->rows as $row) {
            ?>
            <div class="image-box">
                <div class="position-relative bg-gray rounded-xl overflow-hidden w-full h-full border-width-2">
                    <img src="/image/show?code=<?php echo base64_encode($row->file_path . '/poster.jpg'); ?>" alt="" class="img-fluid h-full w-full">
                </div>
                <div class="text-center"><?php echo htmlentities($row->title . '(' . $row->rating . ')');?> <br>
                    <small><?php echo $row->year;?></small>
                </div>
            </div>
            <?php
                }
            }
            ?>
        </div>
    </div>
    <!-- /.card-body -->
</div>