<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">剧集</h3>
        <div class="card-tools">
            <a href="/tv/scan/target/all/" class="btn btn-success btn-sm">扫描剧集库</a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <ul class="cards-vertical">
            <li>
                <div class="w-full">
                    <div class="position-relative image-box overflow-hidden rounded-xl bg-gray bg-cover outline-none shadow">
                        <div class="absolute inset-0 h-full w-full overflow-hidden">
                            <span class="border-box">
                                <img alt src="" class="absolute inset-0 h-full w-full" />
                            </span>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <!-- /.card-body -->
</div>